; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28106.4 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?vertex_shader_code@@3PEBDEB			; vertex_shader_code
PUBLIC	??_C@_0BKD@CGJAHFA@?1?1?5?$CDversion?5300?5es?6?5?5?$CDversion?54@ ; `string'
PUBLIC	?fragment_shader_code@@3PEBDEB			; fragment_shader_code
PUBLIC	??_C@_0OG@KMIJBHIA@?1?1?5?$CDversion?5300?5es?6?5?5?$CDversion?54@ ; `string'
PUBLIC	?orbit@@3UOrbit@XGK@@A				; orbit
PUBLIC	?orbit_object@@3UObject@XGK@@A			; orbit_object
PUBLIC	?orbit_transition@@3UTransition@XGK@@A		; orbit_transition
PUBLIC	?uniform_data@@3PAEA				; uniform_data
PUBLIC	?q@@3PAMA					; q
PUBLIC	?t@@3PAMA					; t
_BSS	SEGMENT
?orbit@@3UOrbit@XGK@@A DB 0a0H DUP (?)			; orbit
?orbit_object@@3UObject@XGK@@A DB 080H DUP (?)		; orbit_object
?orbit_transition@@3UTransition@XGK@@A DB 030H DUP (?)	; orbit_transition
?uniform_data@@3PAEA DB 080H DUP (?)			; uniform_data
?q@@3PAMA DD	04H DUP (?)				; q
_BSS	ENDS
CONST	SEGMENT
?vertices@@3QBMB DD 0bf800000r			; -1	; vertices
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
CONST	ENDS
;	COMDAT ??_C@_0OG@KMIJBHIA@?1?1?5?$CDversion?5300?5es?6?5?5?$CDversion?54@
CONST	SEGMENT
??_C@_0OG@KMIJBHIA@?1?1?5?$CDversion?5300?5es?6?5?5?$CDversion?54@ DB '//'
	DB	' #version 300 es', 0aH, '  #version 440', 0aH, '  #extension '
	DB	'GL_ARB_separate_shader_objects : enable', 0aH, '  precision h'
	DB	'ighp float;', 0aH, 0aH, '  layout (location = 0) out vec4 out'
	DB	'putColor;', 0aH, 0aH, '  void main (void) {', 0aH, '    outpu'
	DB	'tColor = vec4(1.0, 1.0, 0.0, 1.0);', 0aH, '  }', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BKD@CGJAHFA@?1?1?5?$CDversion?5300?5es?6?5?5?$CDversion?54@
CONST	SEGMENT
??_C@_0BKD@CGJAHFA@?1?1?5?$CDversion?5300?5es?6?5?5?$CDversion?54@ DB '//'
	DB	' #version 300 es', 0aH, '  #version 440', 0aH, '  #extension '
	DB	'GL_ARB_separate_shader_objects : enable', 0aH, '  precision h'
	DB	'ighp float;', 0aH, 0aH, '  layout (location = 0) in vec3 vert'
	DB	'ex_data;', 0aH, 0aH, '  // out gl_PerVertex {', 0aH, '  //   '
	DB	'vec4 gl_Position;', 0aH, '  // };', 0aH, 0aH, '  layout (bind'
	DB	'ing = 0) uniform camera {', 0aH, '    mat4 view_mat;', 0aH, ' '
	DB	'   mat4 proj_mat;', 0aH, '  };', 0aH, 0aH, '  out vec4 positi'
	DB	'on;', 0aH, 0aH, '  void main (void) {', 0aH, '    gl_Position'
	DB	' = proj_mat * view_mat * vec4(vertex_data * 2.0, 1.0);', 0aH, ' '
	DB	' }', 0aH, 00H				; `string'
CONST	ENDS
_DATA	SEGMENT
?vertex_shader_code@@3PEBDEB DQ FLAT:??_C@_0BKD@CGJAHFA@?1?1?5?$CDversion?5300?5es?6?5?5?$CDversion?54@ ; vertex_shader_code
?fragment_shader_code@@3PEBDEB DQ FLAT:??_C@_0OG@KMIJBHIA@?1?1?5?$CDversion?5300?5es?6?5?5?$CDversion?54@ ; fragment_shader_code
?t@@3PAMA DD	000000000r			; 0	; t
	DD	000000000r			; 0
	DD	0c1200000r			; -10
	DD	000000000r			; 0
_DATA	ENDS
PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_l
PUBLIC	fprintf
PUBLIC	?_Adjust_manually_vector_aligned@std@@YAXAEAPEAXAEA_K@Z ; std::_Adjust_manually_vector_aligned
PUBLIC	?_Orphan_all@_Container_base0@std@@QEAAXXZ	; std::_Container_base0::_Orphan_all
PUBLIC	?_Alloc_proxy@_Container_base0@std@@QEAAXAEBU_Fake_allocator@2@@Z ; std::_Container_base0::_Alloc_proxy
PUBLIC	??1thread@std@@QEAA@XZ				; std::thread::~thread
PUBLIC	?joinable@thread@std@@QEBA_NXZ			; std::thread::joinable
PUBLIC	?join@thread@std@@QEAAXXZ			; std::thread::join
PUBLIC	?simd32@DATA@XGK@@YAXXZ				; XGK::DATA::simd32
PUBLIC	??0?$allocator@PEAUTransition@XGK@@@std@@QEAA@XZ ; std::allocator<XGK::Transition *>::allocator<XGK::Transition *>
PUBLIC	?deallocate@?$allocator@PEAUTransition@XGK@@@std@@QEAAXQEAPEAUTransition@XGK@@_K@Z ; std::allocator<XGK::Transition *>::deallocate
PUBLIC	??0?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::vector<XGK::Transition *,std::allocator<XGK::Transition *> >
PUBLIC	??1?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::~vector<XGK::Transition *,std::allocator<XGK::Transition *> >
PUBLIC	?_Destroy@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAXPEAPEAUTransition@XGK@@0@Z ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::_Destroy
PUBLIC	?_Tidy@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAXXZ ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::_Tidy
PUBLIC	?_Getal@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAAEAV?$allocator@PEAUTransition@XGK@@@2@XZ ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::_Getal
PUBLIC	??0?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ ; std::_Vector_val<std::_Simple_types<XGK::Transition *> >::_Vector_val<std::_Simple_types<XGK::Transition *> >
PUBLIC	?_Get_first@?$_Compressed_pair@V?$allocator@PEAUTransition@XGK@@@std@@V?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@2@$00@std@@QEAAAEAV?$allocator@PEAUTransition@XGK@@@2@XZ ; std::_Compressed_pair<std::allocator<XGK::Transition *>,std::_Vector_val<std::_Simple_types<XGK::Transition *> >,1>::_Get_first
PUBLIC	??0Time@XGK@@QEAA@XZ				; XGK::Time::Time
PUBLIC	??1Time@XGK@@QEAA@XZ				; XGK::Time::~Time
PUBLIC	?glfw_key_callback@@YAXPEAUGLFWwindow@@HHHH@Z	; glfw_key_callback
PUBLIC	?glfw_error_callback@@YAXHPEBD@Z		; glfw_error_callback
PUBLIC	?transition_thread_function@@YAXXZ		; transition_thread_function
PUBLIC	main
PUBLIC	??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z	; std::thread::thread<void (__cdecl&)(void),void>
PUBLIC	??$?0$$V@?$_Compressed_pair@V?$allocator@PEAUTransition@XGK@@@std@@V?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@@Z ; std::_Compressed_pair<std::allocator<XGK::Transition *>,std::_Vector_val<std::_Simple_types<XGK::Transition *> >,1>::_Compressed_pair<std::allocator<XGK::Transition *>,std::_Vector_val<std::_Simple_types<XGK::Transition *> >,1><>
PUBLIC	??$_Deallocate@$0BA@$0A@@std@@YAXPEAX_K@Z	; std::_Deallocate<16,0>
PUBLIC	??$_Destroy_range@V?$allocator@PEAUTransition@XGK@@@std@@@std@@YAXPEAPEAUTransition@XGK@@QEAPEAU12@AEAV?$allocator@PEAUTransition@XGK@@@0@@Z ; std::_Destroy_range<std::allocator<XGK::Transition *> >
PUBLIC	??$forward@A6AXXZ@std@@YAA6AXXZA6AXXZ@Z		; std::forward<void (__cdecl&)(void)>
PUBLIC	??$make_unique@V?$tuple@P6AXXZ@std@@A6AXXZ$0A@@std@@YA?AV?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@0@A6AXXZ@Z ; std::make_unique<std::tuple<void (__cdecl*)(void)>,void (__cdecl&)(void),0>
PUBLIC	??R?$default_delete@V?$tuple@P6AXXZ@std@@@std@@QEBAXPEAV?$tuple@P6AXXZ@1@@Z ; std::default_delete<std::tuple<void (__cdecl*)(void)> >::operator()
PUBLIC	??1?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@XZ ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::~unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >
PUBLIC	??D?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEBAAEAV?$tuple@P6AXXZ@1@XZ ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::operator*
PUBLIC	?get@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEBAPEAV?$tuple@P6AXXZ@2@XZ ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::get
PUBLIC	?release@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAAPEAV?$tuple@P6AXXZ@2@XZ ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::release
PUBLIC	?_Get_first@?$_Compressed_pair@U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@PEAV?$tuple@P6AXXZ@2@$00@std@@QEAAAEAU?$default_delete@V?$tuple@P6AXXZ@std@@@2@XZ ; std::_Compressed_pair<std::default_delete<std::tuple<void (__cdecl*)(void)> >,std::tuple<void (__cdecl*)(void)> *,1>::_Get_first
PUBLIC	??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z ; std::thread::_Invoke<std::tuple<void (__cdecl*)(void)>,0>
PUBLIC	??$exchange@PEAV?$tuple@P6AXXZ@std@@PEAV12@@std@@YAPEAV?$tuple@P6AXXZ@0@AEAPEAV10@$$QEAPEAV10@@Z ; std::exchange<std::tuple<void (__cdecl*)(void)> *,std::tuple<void (__cdecl*)(void)> *>
PUBLIC	??$?0P6AXXZ$0A@@?$tuple@P6AXXZ@std@@QEAA@AEBQ6AXXZ@Z ; std::tuple<void (__cdecl*)(void)>::tuple<void (__cdecl*)(void)><void (__cdecl*)(void),0>
PUBLIC	??$?0U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@$0A@@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@PEAV?$tuple@P6AXXZ@1@@Z ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > ><std::default_delete<std::tuple<void (__cdecl*)(void)> >,0>
PUBLIC	??$get@$0A@P6AXXZ@std@@YAAEAP6AXXZAEAV?$tuple@P6AXXZ@0@@Z ; std::get<0,void (__cdecl*)(void)>
PUBLIC	??$move@AEAP6AXXZ@std@@YA$$QEAP6AXXZAEAP6AXXZ@Z	; std::move<void (__cdecl*&)(void)>
PUBLIC	??$forward@P6AXXZ@std@@YA$$QEAP6AXXZAEAP6AXXZ@Z	; std::forward<void (__cdecl*)(void)>
PUBLIC	??$_Call@P6AXXZ$$V@_Invoker_functor@std@@SAX$$QEAP6AXXZ@Z ; std::_Invoker_functor::_Call<void (__cdecl*)(void)>
PUBLIC	??$invoke@P6AXXZ$$V@std@@YAX$$QEAP6AXXZ@Z	; std::invoke<void (__cdecl*)(void)>
PUBLIC	??$?0U_Exact_args_t@std@@AEBQ6AXXZ$$V$0A@@?$tuple@P6AXXZ@std@@QEAA@U_Exact_args_t@1@AEBQ6AXXZ@Z ; std::tuple<void (__cdecl*)(void)>::tuple<void (__cdecl*)(void)><std::_Exact_args_t,void (__cdecl*const &)(void),0>
PUBLIC	??$?0AEAPEAV?$tuple@P6AXXZ@std@@@?$_Compressed_pair@U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@PEAV?$tuple@P6AXXZ@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@AEAPEAV?$tuple@P6AXXZ@1@@Z ; std::_Compressed_pair<std::default_delete<std::tuple<void (__cdecl*)(void)> >,std::tuple<void (__cdecl*)(void)> *,1>::_Compressed_pair<std::default_delete<std::tuple<void (__cdecl*)(void)> >,std::tuple<void (__cdecl*)(void)> *,1><std::tuple<void (__cdecl*)(void)> * &>
PUBLIC	??$forward@AEBQ6AXXZ@std@@YAAEBQ6AXXZAEBQ6AXXZ@Z ; std::forward<void (__cdecl*const &)(void)>
PUBLIC	??$?0U_Exact_args_t@std@@$0A@@?$tuple@$$V@std@@QEAA@U_Exact_args_t@1@@Z ; std::tuple<>::tuple<><std::_Exact_args_t,0>
PUBLIC	??$?0AEBQ6AXXZ@?$_Tuple_val@P6AXXZ@std@@QEAA@AEBQ6AXXZ@Z ; std::_Tuple_val<void (__cdecl*)(void)>::_Tuple_val<void (__cdecl*)(void)><void (__cdecl*const &)(void)>
PUBLIC	??$forward@AEAPEAV?$tuple@P6AXXZ@std@@@std@@YAAEAPEAV?$tuple@P6AXXZ@0@AEAPEAV10@@Z ; std::forward<std::tuple<void (__cdecl*)(void)> * &>
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	?time_@@3UTime@XGK@@A				; time_
PUBLIC	??_C@_0L@DCCGFMBN@Error?3?5?$CFs?6@		; `string'
PUBLIC	??_C@_0P@MANJCCCM@Simple?5example@		; `string'
PUBLIC	__real@3c23d70a
PUBLIC	__real@3f800000
PUBLIC	__real@3faaaaab
PUBLIC	__real@42340000
PUBLIC	__real@44fa0000
EXTRN	??2@YAPEAX_K@Z:PROC				; operator new
EXTRN	??3@YAXPEAX_K@Z:PROC				; operator delete
EXTRN	atexit:PROC
EXTRN	__imp__invalid_parameter_noinfo_noreturn:PROC
EXTRN	__imp___acrt_iob_func:PROC
EXTRN	__imp___stdio_common_vfprintf:PROC
EXTRN	__imp_terminate:PROC
EXTRN	__imp__beginthreadex:PROC
EXTRN	_Thrd_join:PROC
EXTRN	_Thrd_id:PROC
EXTRN	_Cnd_do_broadcast_at_thread_exit:PROC
EXTRN	?_Throw_Cpp_error@std@@YAXH@Z:PROC		; std::_Throw_Cpp_error
EXTRN	gladLoadGL:PROC
EXTRN	glfwInit:PROC
EXTRN	glfwTerminate:PROC
EXTRN	glfwSetErrorCallback:PROC
EXTRN	glfwWindowHint:PROC
EXTRN	glfwCreateWindow:PROC
EXTRN	glfwPollEvents:PROC
EXTRN	glfwSetKeyCallback:PROC
EXTRN	glfwMakeContextCurrent:PROC
EXTRN	glfwSwapBuffers:PROC
EXTRN	glfwSwapInterval:PROC
EXTRN	?simd32@VEC4@DATA@XGK@@YAXXZ:PROC		; XGK::DATA::VEC4::simd32
EXTRN	?simd32@QUAT@DATA@XGK@@YAXXZ:PROC		; XGK::DATA::QUAT::simd32
EXTRN	?ident@MAT4@DATA@XGK@@YAXPEAX@Z:PROC		; XGK::DATA::MAT4::ident
EXTRN	?print@MAT4@DATA@XGK@@YAXPEAX@Z:PROC		; XGK::DATA::MAT4::print
EXTRN	?simd32@MAT4@DATA@XGK@@YAXXZ:PROC		; XGK::DATA::MAT4::simd32
EXTRN	?init@TIME@XGK@@YAXPEAUTime@2@_K@Z:PROC		; XGK::TIME::init
EXTRN	?updateTransitions@TIME@XGK@@YAXPEAUTime@2@@Z:PROC ; XGK::TIME::updateTransitions
EXTRN	?getFrameTime@TIME@XGK@@YAXPEAUTime@2@@Z:PROC	; XGK::TIME::getFrameTime
EXTRN	__CxxFrameHandler4:PROC
EXTRN	glad_glClear:QWORD
EXTRN	glad_glViewport:QWORD
EXTRN	glad_glDrawArrays:QWORD
EXTRN	glad_glBindBuffer:QWORD
EXTRN	glad_glGenBuffers:QWORD
EXTRN	glad_glBufferData:QWORD
EXTRN	glad_glBufferSubData:QWORD
EXTRN	glad_glAttachShader:QWORD
EXTRN	glad_glCompileShader:QWORD
EXTRN	glad_glCreateProgram:QWORD
EXTRN	glad_glCreateShader:QWORD
EXTRN	glad_glEnableVertexAttribArray:QWORD
EXTRN	glad_glLinkProgram:QWORD
EXTRN	glad_glShaderSource:QWORD
EXTRN	glad_glUseProgram:QWORD
EXTRN	glad_glVertexAttribPointer:QWORD
EXTRN	glad_glBindBufferBase:QWORD
EXTRN	?makeRotX@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::QUAT::makeRotX
EXTRN	?postRotX@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::QUAT::postRotX
EXTRN	?makeTrans@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA:QWORD	; XGK::DATA::MAT4::makeTrans
EXTRN	?postRotQuat@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA:QWORD ; XGK::DATA::MAT4::postRotQuat
EXTRN	?makeProjPersp@MAT4@DATA@XGK@@3P6AXPEAXMMMMM@ZEA:QWORD ; XGK::DATA::MAT4::makeProjPersp
EXTRN	_fltused:DWORD
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
_BSS	SEGMENT
?time_@@3UTime@XGK@@A DB 040H DUP (?)			; time_
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN4
	DD	imagerel $LN4+81
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$fprintf DD imagerel $LN6
	DD	imagerel $LN6+69
	DD	imagerel $unwind$fprintf
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Adjust_manually_vector_aligned@std@@YAXAEAPEAXAEA_K@Z DD imagerel $LN13
	DD	imagerel $LN13+43
	DD	imagerel $unwind$?_Adjust_manually_vector_aligned@std@@YAXAEAPEAXAEA_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1thread@std@@QEAA@XZ DD imagerel $LN9
	DD	imagerel $LN9+22
	DD	imagerel $unwind$??1thread@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?join@thread@std@@QEAAXXZ DD imagerel $LN14
	DD	imagerel $LN14+94
	DD	imagerel $unwind$?join@thread@std@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?simd32@DATA@XGK@@YAXXZ DD imagerel $LN4
	DD	imagerel $LN4+23
	DD	imagerel $unwind$?simd32@DATA@XGK@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?deallocate@?$allocator@PEAUTransition@XGK@@@std@@QEAAXQEAPEAUTransition@XGK@@_K@Z DD imagerel $LN21
	DD	imagerel $LN21+67
	DD	imagerel $unwind$?deallocate@?$allocator@PEAUTransition@XGK@@@std@@QEAAXQEAPEAUTransition@XGK@@_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ DD imagerel $LN28
	DD	imagerel $LN28+92
	DD	imagerel $unwind$??1?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Tidy@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAXXZ DD imagerel $LN25
	DD	imagerel $LN25+92
	DD	imagerel $unwind$?_Tidy@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1Time@XGK@@QEAA@XZ DD imagerel $LN31
	DD	imagerel $LN31+92
	DD	imagerel $unwind$??1Time@XGK@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__Ftime_@@YAXXZ DD imagerel ??__Ftime_@@YAXXZ
	DD	imagerel ??__Ftime_@@YAXXZ+103
	DD	imagerel $unwind$??__Ftime_@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?glfw_key_callback@@YAXPEAUGLFWwindow@@HHHH@Z DD imagerel $LN5
	DD	imagerel $LN5+92
	DD	imagerel $unwind$?glfw_key_callback@@YAXPEAUGLFWwindow@@HHHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?glfw_error_callback@@YAXHPEBD@Z DD imagerel $LN4
	DD	imagerel $LN4+43
	DD	imagerel $unwind$?glfw_error_callback@@YAXHPEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?transition_thread_function@@YAXXZ DD imagerel $LN8
	DD	imagerel $LN8+30
	DD	imagerel $unwind$?transition_thread_function@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN62
	DD	imagerel $LN62+805
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z DD imagerel $LN36
	DD	imagerel $LN36+115
	DD	imagerel $unwind$??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Deallocate@$0BA@$0A@@std@@YAXPEAX_K@Z DD imagerel $LN18
	DD	imagerel $LN18+53
	DD	imagerel $unwind$??$_Deallocate@$0BA@$0A@@std@@YAXPEAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$make_unique@V?$tuple@P6AXXZ@std@@A6AXXZ$0A@@std@@YA?AV?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@0@A6AXXZ@Z DD imagerel $LN20
	DD	imagerel $LN20+72
	DD	imagerel $unwind$??$make_unique@V?$tuple@P6AXXZ@std@@A6AXXZ$0A@@std@@YA?AV?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@0@A6AXXZ@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z DD imagerel $LN20
	DD	imagerel $LN20+40
	DD	imagerel $unwind$??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
?time_$initializer$@@3P6AXXZEA DQ FLAT:??__Etime_@@YAXXZ ; time_$initializer$
CRT$XCU	ENDS
;	COMDAT __real@44fa0000
CONST	SEGMENT
__real@44fa0000 DD 044fa0000r			; 2000
CONST	ENDS
;	COMDAT __real@42340000
CONST	SEGMENT
__real@42340000 DD 042340000r			; 45
CONST	ENDS
;	COMDAT __real@3faaaaab
CONST	SEGMENT
__real@3faaaaab DD 03faaaaabr			; 1.33333
CONST	ENDS
;	COMDAT __real@3f800000
CONST	SEGMENT
__real@3f800000 DD 03f800000r			; 1
CONST	ENDS
;	COMDAT __real@3c23d70a
CONST	SEGMENT
__real@3c23d70a DD 03c23d70ar			; 0.01
CONST	ENDS
;	COMDAT ??_C@_0P@MANJCCCM@Simple?5example@
CONST	SEGMENT
??_C@_0P@MANJCCCM@Simple?5example@ DB 'Simple example', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@DCCGFMBN@Error?3?5?$CFs?6@
CONST	SEGMENT
??_C@_0L@DCCGFMBN@Error?3?5?$CFs?6@ DB 'Error: %s', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z DB 02H
	DB	012H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z DB 060H
	DD	imagerel $ip2state$??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z DD 020619H
	DD	030023206H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$make_unique@V?$tuple@P6AXXZ@std@@A6AXXZ$0A@@std@@YA?AV?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@0@A6AXXZ@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Deallocate@$0BA@$0A@@std@@YAXPEAX_K@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z DB 04H
	DB	'*'
	DB	00H
	DB	0b0H
	DB	02H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z DB 02H
	DB	0aH
	DD	imagerel ??1?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@XZ
	DB	080H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z DB 028H
	DD	imagerel $stateUnwindMap$??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z
	DD	imagerel $ip2state$??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z DD 040a11H
	DD	09340aH
	DD	07006520aH
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$main DB 08H
	DB	0bdH, 02H
	DB	00H
	DB	0e1H, 07H
	DB	02H
	DB	'n'
	DB	04H
	DB	'n'
	DB	02H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$main DB 04H
	DB	0aH
	DD	imagerel ??1?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@XZ
	DB	01H
	DB	02H
	DB	042H
	DD	imagerel ??1thread@std@@QEAA@XZ
	DB	060H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$main DB 028H
	DD	imagerel $stateUnwindMap$main
	DD	imagerel $ip2state$main
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	060b11H
	DD	0e007720bH
	DD	060047005H
	DD	030025003H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$main
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?transition_thread_function@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?glfw_error_callback@@YAXHPEBD@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?glfw_key_callback@@YAXPEAUGLFWwindow@@HHHH@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__Ftime_@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1Time@XGK@@QEAA@XZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Tidy@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAXXZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?deallocate@?$allocator@PEAUTransition@XGK@@@std@@QEAAXQEAPEAUTransition@XGK@@_K@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?simd32@DATA@XGK@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?join@thread@std@@QEAAXXZ DD 020601H
	DD	030025206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1thread@std@@QEAA@XZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Adjust_manually_vector_aligned@std@@YAXAEAPEAXAEA_K@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$fprintf DD 041601H
	DD	070125216H
	DD	030106011H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 081401H
	DD	0a6414H
	DD	095414H
	DD	083414H
	DD	070105214H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$forward@AEAPEAV?$tuple@P6AXXZ@std@@@std@@YAAEAPEAV?$tuple@P6AXXZ@0@AEAPEAV10@@Z
_TEXT	SEGMENT
_Arg$ = 8
??$forward@AEAPEAV?$tuple@P6AXXZ@std@@@std@@YAAEAPEAV?$tuple@P6AXXZ@0@AEAPEAV10@@Z PROC ; std::forward<std::tuple<void (__cdecl*)(void)> * &>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\type_traits
; Line 1421
	mov	rax, rcx
; Line 1422
	ret	0
??$forward@AEAPEAV?$tuple@P6AXXZ@std@@@std@@YAAEAPEAV?$tuple@P6AXXZ@0@AEAPEAV10@@Z ENDP ; std::forward<std::tuple<void (__cdecl*)(void)> * &>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0AEBQ6AXXZ@?$_Tuple_val@P6AXXZ@std@@QEAA@AEBQ6AXXZ@Z
_TEXT	SEGMENT
this$ = 8
_Arg$ = 16
??$?0AEBQ6AXXZ@?$_Tuple_val@P6AXXZ@std@@QEAA@AEBQ6AXXZ@Z PROC ; std::_Tuple_val<void (__cdecl*)(void)>::_Tuple_val<void (__cdecl*)(void)><void (__cdecl*const &)(void)>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\tuple
; Line 155
	mov	rax, QWORD PTR [rdx]
	mov	QWORD PTR [rcx], rax
; Line 156
	mov	rax, rcx
	ret	0
??$?0AEBQ6AXXZ@?$_Tuple_val@P6AXXZ@std@@QEAA@AEBQ6AXXZ@Z ENDP ; std::_Tuple_val<void (__cdecl*)(void)>::_Tuple_val<void (__cdecl*)(void)><void (__cdecl*const &)(void)>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0U_Exact_args_t@std@@$0A@@?$tuple@$$V@std@@QEAA@U_Exact_args_t@1@@Z
_TEXT	SEGMENT
this$ = 8
__formal$ = 16
??$?0U_Exact_args_t@std@@$0A@@?$tuple@$$V@std@@QEAA@U_Exact_args_t@1@@Z PROC ; std::tuple<>::tuple<><std::_Exact_args_t,0>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\tuple
; Line 215
	mov	rax, rcx
	ret	0
??$?0U_Exact_args_t@std@@$0A@@?$tuple@$$V@std@@QEAA@U_Exact_args_t@1@@Z ENDP ; std::tuple<>::tuple<><std::_Exact_args_t,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$forward@AEBQ6AXXZ@std@@YAAEBQ6AXXZAEBQ6AXXZ@Z
_TEXT	SEGMENT
_Arg$ = 8
??$forward@AEBQ6AXXZ@std@@YAAEBQ6AXXZAEBQ6AXXZ@Z PROC	; std::forward<void (__cdecl*const &)(void)>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\type_traits
; Line 1421
	mov	rax, rcx
; Line 1422
	ret	0
??$forward@AEBQ6AXXZ@std@@YAAEBQ6AXXZAEBQ6AXXZ@Z ENDP	; std::forward<void (__cdecl*const &)(void)>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0AEAPEAV?$tuple@P6AXXZ@std@@@?$_Compressed_pair@U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@PEAV?$tuple@P6AXXZ@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@AEAPEAV?$tuple@P6AXXZ@1@@Z
_TEXT	SEGMENT
this$ = 8
__formal$ = 16
<_Val2_0>$ = 24
??$?0AEAPEAV?$tuple@P6AXXZ@std@@@?$_Compressed_pair@U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@PEAV?$tuple@P6AXXZ@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@AEAPEAV?$tuple@P6AXXZ@1@@Z PROC ; std::_Compressed_pair<std::default_delete<std::tuple<void (__cdecl*)(void)> >,std::tuple<void (__cdecl*)(void)> *,1>::_Compressed_pair<std::default_delete<std::tuple<void (__cdecl*)(void)> >,std::tuple<void (__cdecl*)(void)> *,1><std::tuple<void (__cdecl*)(void)> * &>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1414
	mov	rax, QWORD PTR [r8]
	mov	QWORD PTR [rcx], rax
	mov	rax, rcx
	ret	0
??$?0AEAPEAV?$tuple@P6AXXZ@std@@@?$_Compressed_pair@U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@PEAV?$tuple@P6AXXZ@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@AEAPEAV?$tuple@P6AXXZ@1@@Z ENDP ; std::_Compressed_pair<std::default_delete<std::tuple<void (__cdecl*)(void)> >,std::tuple<void (__cdecl*)(void)> *,1>::_Compressed_pair<std::default_delete<std::tuple<void (__cdecl*)(void)> >,std::tuple<void (__cdecl*)(void)> *,1><std::tuple<void (__cdecl*)(void)> * &>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0U_Exact_args_t@std@@AEBQ6AXXZ$$V$0A@@?$tuple@P6AXXZ@std@@QEAA@U_Exact_args_t@1@AEBQ6AXXZ@Z
_TEXT	SEGMENT
this$ = 8
__formal$ = 16
_This_arg$ = 24
??$?0U_Exact_args_t@std@@AEBQ6AXXZ$$V$0A@@?$tuple@P6AXXZ@std@@QEAA@U_Exact_args_t@1@AEBQ6AXXZ@Z PROC ; std::tuple<void (__cdecl*)(void)>::tuple<void (__cdecl*)(void)><std::_Exact_args_t,void (__cdecl*const &)(void),0>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\tuple
; Line 155
	mov	rax, QWORD PTR [r8]
	mov	QWORD PTR [rcx], rax
; Line 243
	mov	rax, rcx
	ret	0
??$?0U_Exact_args_t@std@@AEBQ6AXXZ$$V$0A@@?$tuple@P6AXXZ@std@@QEAA@U_Exact_args_t@1@AEBQ6AXXZ@Z ENDP ; std::tuple<void (__cdecl*)(void)>::tuple<void (__cdecl*)(void)><std::_Exact_args_t,void (__cdecl*const &)(void),0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$invoke@P6AXXZ$$V@std@@YAX$$QEAP6AXXZ@Z
_TEXT	SEGMENT
_Obj$ = 8
??$invoke@P6AXXZ$$V@std@@YAX$$QEAP6AXXZ@Z PROC		; std::invoke<void (__cdecl*)(void)>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\type_traits
; Line 1571
	rex_jmp	QWORD PTR [rcx]
??$invoke@P6AXXZ$$V@std@@YAX$$QEAP6AXXZ@Z ENDP		; std::invoke<void (__cdecl*)(void)>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$_Call@P6AXXZ$$V@_Invoker_functor@std@@SAX$$QEAP6AXXZ@Z
_TEXT	SEGMENT
_Obj$ = 8
??$_Call@P6AXXZ$$V@_Invoker_functor@std@@SAX$$QEAP6AXXZ@Z PROC ; std::_Invoker_functor::_Call<void (__cdecl*)(void)>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\type_traits
; Line 1571
	rex_jmp	QWORD PTR [rcx]
??$_Call@P6AXXZ$$V@_Invoker_functor@std@@SAX$$QEAP6AXXZ@Z ENDP ; std::_Invoker_functor::_Call<void (__cdecl*)(void)>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$forward@P6AXXZ@std@@YA$$QEAP6AXXZAEAP6AXXZ@Z
_TEXT	SEGMENT
_Arg$ = 8
??$forward@P6AXXZ@std@@YA$$QEAP6AXXZAEAP6AXXZ@Z PROC	; std::forward<void (__cdecl*)(void)>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\type_traits
; Line 1421
	mov	rax, rcx
; Line 1422
	ret	0
??$forward@P6AXXZ@std@@YA$$QEAP6AXXZAEAP6AXXZ@Z ENDP	; std::forward<void (__cdecl*)(void)>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$move@AEAP6AXXZ@std@@YA$$QEAP6AXXZAEAP6AXXZ@Z
_TEXT	SEGMENT
_Arg$ = 8
??$move@AEAP6AXXZ@std@@YA$$QEAP6AXXZAEAP6AXXZ@Z PROC	; std::move<void (__cdecl*&)(void)>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\type_traits
; Line 1433
	mov	rax, rcx
; Line 1434
	ret	0
??$move@AEAP6AXXZ@std@@YA$$QEAP6AXXZAEAP6AXXZ@Z ENDP	; std::move<void (__cdecl*&)(void)>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$get@$0A@P6AXXZ@std@@YAAEAP6AXXZAEAV?$tuple@P6AXXZ@0@@Z
_TEXT	SEGMENT
_Tuple$ = 8
??$get@$0A@P6AXXZ@std@@YAAEAP6AXXZAEAV?$tuple@P6AXXZ@0@@Z PROC ; std::get<0,void (__cdecl*)(void)>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\tuple
; Line 651
	mov	rax, rcx
; Line 652
	ret	0
??$get@$0A@P6AXXZ@std@@YAAEAP6AXXZAEAV?$tuple@P6AXXZ@0@@Z ENDP ; std::get<0,void (__cdecl*)(void)>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@$0A@@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@PEAV?$tuple@P6AXXZ@1@@Z
_TEXT	SEGMENT
this$ = 8
_Ptr$ = 16
??$?0U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@$0A@@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@PEAV?$tuple@P6AXXZ@1@@Z PROC ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > ><std::default_delete<std::tuple<void (__cdecl*)(void)> >,0>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1414
	mov	QWORD PTR [rcx], rdx
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 1820
	mov	rax, rcx
	ret	0
??$?0U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@$0A@@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@PEAV?$tuple@P6AXXZ@1@@Z ENDP ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > ><std::default_delete<std::tuple<void (__cdecl*)(void)> >,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0P6AXXZ$0A@@?$tuple@P6AXXZ@std@@QEAA@AEBQ6AXXZ@Z
_TEXT	SEGMENT
this$ = 8
_This_arg$ = 16
??$?0P6AXXZ$0A@@?$tuple@P6AXXZ@std@@QEAA@AEBQ6AXXZ@Z PROC ; std::tuple<void (__cdecl*)(void)>::tuple<void (__cdecl*)(void)><void (__cdecl*)(void),0>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\tuple
; Line 155
	mov	rax, QWORD PTR [rdx]
	mov	QWORD PTR [rcx], rax
; Line 295
	mov	rax, rcx
	ret	0
??$?0P6AXXZ$0A@@?$tuple@P6AXXZ@std@@QEAA@AEBQ6AXXZ@Z ENDP ; std::tuple<void (__cdecl*)(void)>::tuple<void (__cdecl*)(void)><void (__cdecl*)(void),0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$exchange@PEAV?$tuple@P6AXXZ@std@@PEAV12@@std@@YAPEAV?$tuple@P6AXXZ@0@AEAPEAV10@$$QEAPEAV10@@Z
_TEXT	SEGMENT
_Val$ = 8
_New_val$ = 16
??$exchange@PEAV?$tuple@P6AXXZ@std@@PEAV12@@std@@YAPEAV?$tuple@P6AXXZ@0@AEAPEAV10@$$QEAPEAV10@@Z PROC ; std::exchange<std::tuple<void (__cdecl*)(void)> *,std::tuple<void (__cdecl*)(void)> *>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\utility
; Line 528
	mov	rdx, QWORD PTR [rdx]
	mov	rax, QWORD PTR [rcx]
	mov	QWORD PTR [rcx], rdx
; Line 530
	ret	0
??$exchange@PEAV?$tuple@P6AXXZ@std@@PEAV12@@std@@YAPEAV?$tuple@P6AXXZ@0@AEAPEAV10@$$QEAPEAV10@@Z ENDP ; std::exchange<std::tuple<void (__cdecl*)(void)> *,std::tuple<void (__cdecl*)(void)> *>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z
_TEXT	SEGMENT
_RawVals$ = 48
??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z PROC ; std::thread::_Invoke<std::tuple<void (__cdecl*)(void)>,0>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\thread
; Line 36
$LN20:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\type_traits
; Line 1571
	call	QWORD PTR [rcx]
	npad	1
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\thread
; Line 41
	call	_Cnd_do_broadcast_at_thread_exit
	npad	1
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 1767
	mov	edx, 8
	mov	rcx, rbx
	call	??3@YAXPEAX_K@Z				; operator delete
	npad	1
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\thread
; Line 42
	xor	eax, eax
; Line 43
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z ENDP ; std::thread::_Invoke<std::tuple<void (__cdecl*)(void)>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?_Get_first@?$_Compressed_pair@U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@PEAV?$tuple@P6AXXZ@2@$00@std@@QEAAAEAU?$default_delete@V?$tuple@P6AXXZ@std@@@2@XZ
_TEXT	SEGMENT
this$ = 8
?_Get_first@?$_Compressed_pair@U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@PEAV?$tuple@P6AXXZ@2@$00@std@@QEAAAEAU?$default_delete@V?$tuple@P6AXXZ@std@@@2@XZ PROC ; std::_Compressed_pair<std::default_delete<std::tuple<void (__cdecl*)(void)> >,std::tuple<void (__cdecl*)(void)> *,1>::_Get_first, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1421
	mov	rax, rcx
; Line 1422
	ret	0
?_Get_first@?$_Compressed_pair@U?$default_delete@V?$tuple@P6AXXZ@std@@@std@@PEAV?$tuple@P6AXXZ@2@$00@std@@QEAAAEAU?$default_delete@V?$tuple@P6AXXZ@std@@@2@XZ ENDP ; std::_Compressed_pair<std::default_delete<std::tuple<void (__cdecl*)(void)> >,std::tuple<void (__cdecl*)(void)> *,1>::_Get_first
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?release@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAAPEAV?$tuple@P6AXXZ@2@XZ
_TEXT	SEGMENT
this$ = 8
?release@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAAPEAV?$tuple@P6AXXZ@2@XZ PROC ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::release, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\utility
; Line 527
	mov	rax, QWORD PTR [rcx]
; Line 528
	mov	QWORD PTR [rcx], 0
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 1905
	ret	0
?release@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAAPEAV?$tuple@P6AXXZ@2@XZ ENDP ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::release
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?get@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEBAPEAV?$tuple@P6AXXZ@2@XZ
_TEXT	SEGMENT
this$ = 8
?get@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEBAPEAV?$tuple@P6AXXZ@2@XZ PROC ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::get, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 1896
	mov	rax, QWORD PTR [rcx]
; Line 1897
	ret	0
?get@?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEBAPEAV?$tuple@P6AXXZ@2@XZ ENDP ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::get
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??D?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEBAAEAV?$tuple@P6AXXZ@1@XZ
_TEXT	SEGMENT
this$ = 8
??D?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEBAAEAV?$tuple@P6AXXZ@1@XZ PROC ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::operator*, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 1888
	mov	rax, QWORD PTR [rcx]
; Line 1889
	ret	0
??D?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEBAAEAV?$tuple@P6AXXZ@1@XZ ENDP ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::operator*
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@XZ PROC ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::~unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 1874
	mov	rcx, QWORD PTR [rcx]
	test	rcx, rcx
	je	SHORT $LN5@unique_ptr
; Line 1767
	mov	edx, 8
	jmp	??3@YAXPEAX_K@Z				; operator delete
$LN5@unique_ptr:
; Line 1877
	ret	0
??1?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@XZ ENDP ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::~unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??R?$default_delete@V?$tuple@P6AXXZ@std@@@std@@QEBAXPEAV?$tuple@P6AXXZ@1@@Z
_TEXT	SEGMENT
this$ = 8
_Ptr$ = 16
??R?$default_delete@V?$tuple@P6AXXZ@std@@@std@@QEBAXPEAV?$tuple@P6AXXZ@1@@Z PROC ; std::default_delete<std::tuple<void (__cdecl*)(void)> >::operator(), COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 1765
	mov	rcx, rdx
; Line 1767
	mov	edx, 8
	jmp	??3@YAXPEAX_K@Z				; operator delete
??R?$default_delete@V?$tuple@P6AXXZ@std@@@std@@QEBAXPEAV?$tuple@P6AXXZ@1@@Z ENDP ; std::default_delete<std::tuple<void (__cdecl*)(void)> >::operator()
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$make_unique@V?$tuple@P6AXXZ@std@@A6AXXZ$0A@@std@@YA?AV?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@0@A6AXXZ@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 48
<_Args_0>$ = 56
??$make_unique@V?$tuple@P6AXXZ@std@@A6AXXZ$0A@@std@@YA?AV?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@0@A6AXXZ@Z PROC ; std::make_unique<std::tuple<void (__cdecl*)(void)>,void (__cdecl&)(void),0>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 2056
$LN20:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	mov	rdi, rdx
; Line 2057
	mov	ecx, 8
	call	??2@YAPEAX_K@Z				; operator new
	test	rax, rax
	je	SHORT $LN3@make_uniqu
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\tuple
; Line 155
	mov	QWORD PTR [rax], rdi
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1414
	mov	QWORD PTR [rbx], rax
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 2058
	mov	rax, rbx
	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
$LN3@make_uniqu:
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1414
	mov	QWORD PTR [rbx], 0
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 2058
	mov	rax, rbx
	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
??$make_unique@V?$tuple@P6AXXZ@std@@A6AXXZ$0A@@std@@YA?AV?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@0@A6AXXZ@Z ENDP ; std::make_unique<std::tuple<void (__cdecl*)(void)>,void (__cdecl&)(void),0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$forward@A6AXXZ@std@@YAA6AXXZA6AXXZ@Z
_TEXT	SEGMENT
_Arg$ = 8
??$forward@A6AXXZ@std@@YAA6AXXZA6AXXZ@Z PROC		; std::forward<void (__cdecl&)(void)>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\type_traits
; Line 1421
	mov	rax, rcx
; Line 1422
	ret	0
??$forward@A6AXXZ@std@@YAA6AXXZA6AXXZ@Z ENDP		; std::forward<void (__cdecl&)(void)>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$_Destroy_range@V?$allocator@PEAUTransition@XGK@@@std@@@std@@YAXPEAPEAUTransition@XGK@@QEAPEAU12@AEAV?$allocator@PEAUTransition@XGK@@@0@@Z
_TEXT	SEGMENT
_First$ = 8
_Last$ = 16
_Al$ = 24
??$_Destroy_range@V?$allocator@PEAUTransition@XGK@@@std@@@std@@YAXPEAPEAUTransition@XGK@@QEAPEAU12@AEAV?$allocator@PEAUTransition@XGK@@@0@@Z PROC ; std::_Destroy_range<std::allocator<XGK::Transition *> >, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1041
	ret	0
??$_Destroy_range@V?$allocator@PEAUTransition@XGK@@@std@@@std@@YAXPEAPEAUTransition@XGK@@QEAPEAU12@AEAV?$allocator@PEAUTransition@XGK@@@0@@Z ENDP ; std::_Destroy_range<std::allocator<XGK::Transition *> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$_Deallocate@$0BA@$0A@@std@@YAXPEAX_K@Z
_TEXT	SEGMENT
_Ptr$ = 48
_Bytes$ = 56
??$_Deallocate@$0BA@$0A@@std@@YAXPEAX_K@Z PROC		; std::_Deallocate<16,0>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 183
$LN18:
	sub	rsp, 40					; 00000028H
; Line 186
	cmp	rdx, 4096				; 00001000H
	jb	SHORT $LN13@Deallocate
; Line 107
	mov	r8, QWORD PTR [rcx-8]
	add	rdx, 39					; 00000027H
; Line 120
	sub	rcx, r8
; Line 121
	lea	rax, QWORD PTR [rcx-8]
	cmp	rax, 31
	ja	SHORT $LN10@Deallocate
; Line 122
	mov	rcx, r8
$LN13@Deallocate:
; Line 192
	add	rsp, 40					; 00000028H
; Line 191
	jmp	??3@YAXPEAX_K@Z				; operator delete
$LN10@Deallocate:
; Line 121
	call	QWORD PTR __imp__invalid_parameter_noinfo_noreturn
	int	3
$LN15@Deallocate:
??$_Deallocate@$0BA@$0A@@std@@YAXPEAX_K@Z ENDP		; std::_Deallocate<16,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0$$V@?$_Compressed_pair@V?$allocator@PEAUTransition@XGK@@@std@@V?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@@Z
_TEXT	SEGMENT
this$ = 8
__formal$ = 16
??$?0$$V@?$_Compressed_pair@V?$allocator@PEAUTransition@XGK@@@std@@V?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@@Z PROC ; std::_Compressed_pair<std::allocator<XGK::Transition *>,std::_Vector_val<std::_Simple_types<XGK::Transition *> >,1>::_Compressed_pair<std::allocator<XGK::Transition *>,std::_Vector_val<std::_Simple_types<XGK::Transition *> >,1><>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 314
	xor	eax, eax
	mov	QWORD PTR [rcx], rax
	mov	QWORD PTR [rcx+8], rax
	mov	QWORD PTR [rcx+16], rax
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1414
	mov	rax, rcx
	ret	0
??$?0$$V@?$_Compressed_pair@V?$allocator@PEAUTransition@XGK@@@std@@V?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@@Z ENDP ; std::_Compressed_pair<std::allocator<XGK::Transition *>,std::_Vector_val<std::_Simple_types<XGK::Transition *> >,1>::_Compressed_pair<std::allocator<XGK::Transition *>,std::_Vector_val<std::_Simple_types<XGK::Transition *> >,1><>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z
_TEXT	SEGMENT
_Decay_copied$ = 64
this$ = 64
_Fx$ = 72
??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z PROC		; std::thread::thread<void (__cdecl&)(void),void>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\thread
; Line 53
$LN36:
	mov	QWORD PTR [rsp+16], rbx
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rdi, rdx
	mov	rbx, rcx
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 2057
	mov	ecx, 8
	call	??2@YAPEAX_K@Z				; operator new
	test	rax, rax
	je	SHORT $LN9@thread
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\tuple
; Line 155
	mov	QWORD PTR [rax], rdi
$LN9@thread:
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1414
	mov	QWORD PTR _Decay_copied$[rsp], rax
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\thread
; Line 62
	lea	rdi, QWORD PTR [rbx+8]
	mov	QWORD PTR [rsp+40], rdi
	mov	DWORD PTR [rsp+32], 0
	mov	r9, rax
	lea	r8, OFFSET FLAT:??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z ; std::thread::_Invoke<std::tuple<void (__cdecl*)(void)>,0>
	xor	edx, edx
	xor	ecx, ecx
	call	QWORD PTR __imp__beginthreadex
	mov	QWORD PTR [rbx], rax
; Line 66
	test	rax, rax
	je	SHORT $LN2@thread
; Line 72
	mov	rax, rbx
	mov	rbx, QWORD PTR [rsp+72]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN2@thread:
; Line 69
	mov	DWORD PTR [rdi], 0
; Line 70
	mov	ecx, 6
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN33@thread:
??$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z ENDP		; std::thread::thread<void (__cdecl&)(void),void>
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
_Decay_copied$ = 64
this$ = 64
_Fx$ = 72
?dtor$0@?0???$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z@4HA PROC ; `std::thread::thread<void (__cdecl&)(void),void>'::`1'::dtor$0
	lea	rcx, QWORD PTR _Decay_copied$[rdx]
	jmp	??1?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@XZ ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::~unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >
?dtor$0@?0???$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z@4HA ENDP ; `std::thread::thread<void (__cdecl&)(void),void>'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Ogtpy
;	COMDAT text$x
text$x	SEGMENT
_Decay_copied$ = 64
this$ = 64
_Fx$ = 72
?dtor$0@?0???$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z@4HA PROC ; `std::thread::thread<void (__cdecl&)(void),void>'::`1'::dtor$0
	lea	rcx, QWORD PTR _Decay_copied$[rdx]
	jmp	??1?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@XZ ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::~unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >
?dtor$0@?0???$?0A6AXXZ$$VX@thread@std@@QEAA@A6AXXZ@Z@4HA ENDP ; `std::thread::thread<void (__cdecl&)(void),void>'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
transition_thread$ = 48
uniform_buffer$ = 112
vertex_buffer$ = 120
_Decay_copied$1 = 128
main	PROC						; COMDAT
; File E:\reps\denis-belov\c-test\xgk\src\test.cpp
; Line 74
$LN62:
	push	rbx
	push	rbp
	push	rsi
	push	rdi
	push	r14
	sub	rsp, 64					; 00000040H
; Line 76
	call	glfwInit
	test	eax, eax
	je	SHORT $LN59@main
; Line 81
	xor	r14d, r14d
	mov	QWORD PTR [rsp+32], r14
	xor	r9d, r9d
	lea	r8, OFFSET FLAT:??_C@_0P@MANJCCCM@Simple?5example@
	mov	edx, 480				; 000001e0H
	mov	ecx, 640				; 00000280H
	call	glfwCreateWindow
	mov	rbp, rax
; Line 83
	test	rax, rax
	jne	SHORT $LN5@main
; Line 85
	call	glfwTerminate
$LN59@main:
; Line 201
	mov	eax, 1
	add	rsp, 64					; 00000040H
	pop	r14
	pop	rdi
	pop	rsi
	pop	rbp
	pop	rbx
	ret	0
$LN5@main:
; Line 90
	mov	rcx, rbp
	call	glfwMakeContextCurrent
; Line 91
	lea	rcx, OFFSET FLAT:?glfw_error_callback@@YAXHPEBD@Z ; glfw_error_callback
	call	glfwSetErrorCallback
; Line 92
	mov	edx, 2
	mov	ecx, 139266				; 00022002H
	call	glfwWindowHint
; Line 93
	xor	edx, edx
	mov	ecx, 139267				; 00022003H
	call	glfwWindowHint
; Line 94
	mov	ecx, 1
	call	glfwSwapInterval
; Line 95
	lea	rdx, OFFSET FLAT:?glfw_key_callback@@YAXPEAUGLFWwindow@@HHHH@Z ; glfw_key_callback
	mov	rcx, rbp
	call	glfwSetKeyCallback
; Line 97
	call	gladLoadGL
; Line 99
	xor	edx, edx
	xor	ecx, ecx
	mov	r9d, 480				; 000001e0H
	mov	r8d, 640				; 00000280H
	call	QWORD PTR glad_glViewport
; Line 104
	mov	edx, 8
	lea	rcx, OFFSET FLAT:?time_@@3UTime@XGK@@A	; time_
	call	?init@TIME@XGK@@YAXPEAUTime@2@_K@Z	; XGK::TIME::init
; File E:\reps\denis-belov\xgk\src\data\data.h
; Line 181
	call	?simd32@VEC4@DATA@XGK@@YAXXZ		; XGK::DATA::VEC4::simd32
; Line 182
	call	?simd32@QUAT@DATA@XGK@@YAXXZ		; XGK::DATA::QUAT::simd32
; Line 183
	call	?simd32@MAT4@DATA@XGK@@YAXXZ		; XGK::DATA::MAT4::simd32
; File E:\reps\denis-belov\c-test\xgk\src\test.cpp
; Line 110
	movss	xmm1, DWORD PTR __real@3c23d70a
	lea	rcx, OFFSET FLAT:?q@@3PAMA		; q
	call	QWORD PTR ?makeRotX@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::QUAT::makeRotX
; Line 111
	lea	rcx, OFFSET FLAT:?uniform_data@@3PAEA	; uniform_data
	call	?ident@MAT4@DATA@XGK@@YAXPEAX@Z		; XGK::DATA::MAT4::ident
; Line 112
	lea	rdx, OFFSET FLAT:?t@@3PAMA		; t
	lea	rcx, OFFSET FLAT:?uniform_data@@3PAEA	; uniform_data
	call	QWORD PTR ?makeTrans@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA ; XGK::DATA::MAT4::makeTrans
; Line 113
	movss	xmm3, DWORD PTR __real@3f800000
	movss	DWORD PTR [rsp+40], xmm3
	movss	xmm0, DWORD PTR __real@44fa0000
	movss	DWORD PTR [rsp+32], xmm0
	movss	xmm2, DWORD PTR __real@3faaaaab
	movss	xmm1, DWORD PTR __real@42340000
	lea	rcx, OFFSET FLAT:?uniform_data@@3PAEA+64
	call	QWORD PTR ?makeProjPersp@MAT4@DATA@XGK@@3P6AXPEAXMMMMM@ZEA ; XGK::DATA::MAT4::makeProjPersp
; Line 115
	lea	rcx, OFFSET FLAT:?uniform_data@@3PAEA	; uniform_data
	call	?print@MAT4@DATA@XGK@@YAXPEAX@Z		; XGK::DATA::MAT4::print
; Line 128
	lea	rdx, QWORD PTR uniform_buffer$[rsp]
	mov	ecx, 1
	call	QWORD PTR glad_glGenBuffers
; Line 129
	mov	edx, DWORD PTR uniform_buffer$[rsp]
	mov	ecx, 35345				; 00008a11H
	call	QWORD PTR glad_glBindBuffer
; Line 130
	mov	r9d, 35048				; 000088e8H
	lea	r8, OFFSET FLAT:?uniform_data@@3PAEA	; uniform_data
	mov	edx, 128				; 00000080H
	mov	ecx, 35345				; 00008a11H
	call	QWORD PTR glad_glBufferData
; Line 131
	mov	r8d, DWORD PTR uniform_buffer$[rsp]
	xor	edx, edx
	mov	ecx, 35345				; 00008a11H
	call	QWORD PTR glad_glBindBufferBase
; Line 136
	lea	rdx, QWORD PTR vertex_buffer$[rsp]
	mov	ecx, 1
	call	QWORD PTR glad_glGenBuffers
; Line 137
	mov	edx, DWORD PTR vertex_buffer$[rsp]
	mov	ecx, 34962				; 00008892H
	call	QWORD PTR glad_glBindBuffer
; Line 138
	mov	r9d, 35044				; 000088e4H
	lea	r8, OFFSET FLAT:?vertices@@3QBMB
	mov	edx, 72					; 00000048H
	lea	ecx, QWORD PTR [r9-82]
	call	QWORD PTR glad_glBufferData
; Line 140
	mov	ecx, 35633				; 00008b31H
	call	QWORD PTR glad_glCreateShader
	mov	esi, eax
; Line 141
	xor	r9d, r9d
	lea	r8, OFFSET FLAT:?vertex_shader_code@@3PEBDEB ; vertex_shader_code
	lea	edx, QWORD PTR [r9+1]
	mov	ecx, eax
	call	QWORD PTR glad_glShaderSource
; Line 142
	mov	ecx, esi
	call	QWORD PTR glad_glCompileShader
; Line 144
	mov	ecx, 35632				; 00008b30H
	call	QWORD PTR glad_glCreateShader
	mov	edi, eax
; Line 145
	xor	r9d, r9d
	lea	r8, OFFSET FLAT:?fragment_shader_code@@3PEBDEB ; fragment_shader_code
	lea	edx, QWORD PTR [r9+1]
	mov	ecx, eax
	call	QWORD PTR glad_glShaderSource
; Line 146
	mov	ecx, edi
	call	QWORD PTR glad_glCompileShader
; Line 148
	call	QWORD PTR glad_glCreateProgram
	mov	ebx, eax
; Line 149
	mov	edx, esi
	mov	ecx, eax
	call	QWORD PTR glad_glAttachShader
; Line 150
	mov	edx, edi
	mov	ecx, ebx
	call	QWORD PTR glad_glAttachShader
; Line 151
	mov	ecx, ebx
	call	QWORD PTR glad_glLinkProgram
; Line 153
	mov	ecx, ebx
	call	QWORD PTR glad_glUseProgram
; Line 157
	xor	ecx, ecx
	call	QWORD PTR glad_glEnableVertexAttribArray
; Line 158
	mov	QWORD PTR [rsp+40], r14
	mov	DWORD PTR [rsp+32], r14d
	xor	r9d, r9d
	lea	edx, QWORD PTR [r9+3]
	xor	ecx, ecx
	mov	r8d, 5126				; 00001406H
	call	QWORD PTR glad_glVertexAttribPointer
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 2057
	mov	ecx, 8
	call	??2@YAPEAX_K@Z				; operator new
	test	rax, rax
	je	SHORT $LN17@main
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\tuple
; Line 155
	lea	rcx, OFFSET FLAT:?transition_thread_function@@YAXXZ ; transition_thread_function
	mov	QWORD PTR [rax], rcx
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory
; Line 2057
	jmp	SHORT $LN18@main
$LN17@main:
	mov	rax, r14
$LN18@main:
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1414
	mov	QWORD PTR _Decay_copied$1[rsp], rax
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\thread
; Line 62
	lea	rcx, QWORD PTR transition_thread$[rsp+8]
	mov	QWORD PTR [rsp+40], rcx
	mov	DWORD PTR [rsp+32], r14d
	mov	r9, rax
	lea	r8, OFFSET FLAT:??$_Invoke@V?$tuple@P6AXXZ@std@@$0A@@thread@std@@CAIPEAX@Z ; std::thread::_Invoke<std::tuple<void (__cdecl*)(void)>,0>
	xor	edx, edx
	xor	ecx, ecx
	call	QWORD PTR __imp__beginthreadex
	mov	QWORD PTR transition_thread$[rsp], rax
; Line 66
	test	rax, rax
	je	SHORT $LN11@main
$LL2@main:
; File E:\reps\denis-belov\c-test\xgk\src\test.cpp
; Line 178
	call	glfwPollEvents
; Line 180
	mov	ecx, 16384				; 00004000H
	call	QWORD PTR glad_glClear
; Line 186
	lea	r9, OFFSET FLAT:?uniform_data@@3PAEA	; uniform_data
	xor	edx, edx
	mov	ecx, 35345				; 00008a11H
	lea	r8d, QWORD PTR [rdx+64]
	call	QWORD PTR glad_glBufferSubData
; Line 188
	xor	edx, edx
	lea	ecx, QWORD PTR [rdx+4]
	lea	r8d, QWORD PTR [rdx+6]
	call	QWORD PTR glad_glDrawArrays
; Line 190
	mov	rcx, rbp
	call	glfwSwapBuffers
; Line 191
	jmp	SHORT $LL2@main
$LN11@main:
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\thread
; Line 69
	mov	DWORD PTR transition_thread$[rsp+8], r14d
; Line 70
	mov	ecx, 6
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN58@main:
main	ENDP
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
transition_thread$ = 48
uniform_buffer$ = 112
vertex_buffer$ = 120
_Decay_copied$1 = 128
main$dtor$1 PROC
	lea	rcx, QWORD PTR _Decay_copied$1[rdx]
	jmp	??1?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@XZ ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::~unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >
main$dtor$1 ENDP
text$x	ENDS
;	COMDAT text$x
text$x	SEGMENT
transition_thread$ = 48
uniform_buffer$ = 112
vertex_buffer$ = 120
_Decay_copied$1 = 128
main$dtor$0 PROC
	lea	rcx, QWORD PTR transition_thread$[rdx]
	jmp	??1thread@std@@QEAA@XZ			; std::thread::~thread
main$dtor$0 ENDP
text$x	ENDS
; Function compile flags: /Ogtpy
;	COMDAT text$x
text$x	SEGMENT
transition_thread$ = 48
uniform_buffer$ = 112
vertex_buffer$ = 120
_Decay_copied$1 = 128
main$dtor$1 PROC
	lea	rcx, QWORD PTR _Decay_copied$1[rdx]
	jmp	??1?$unique_ptr@V?$tuple@P6AXXZ@std@@U?$default_delete@V?$tuple@P6AXXZ@std@@@2@@std@@QEAA@XZ ; std::unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >::~unique_ptr<std::tuple<void (__cdecl*)(void)>,std::default_delete<std::tuple<void (__cdecl*)(void)> > >
main$dtor$1 ENDP
text$x	ENDS
; Function compile flags: /Ogtpy
;	COMDAT text$x
text$x	SEGMENT
transition_thread$ = 48
uniform_buffer$ = 112
vertex_buffer$ = 120
_Decay_copied$1 = 128
main$dtor$0 PROC
	lea	rcx, QWORD PTR transition_thread$[rdx]
	jmp	??1thread@std@@QEAA@XZ			; std::thread::~thread
main$dtor$0 ENDP
text$x	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?transition_thread_function@@YAXXZ
_TEXT	SEGMENT
?transition_thread_function@@YAXXZ PROC			; transition_thread_function, COMDAT
; File E:\reps\denis-belov\c-test\xgk\src\test.cpp
; Line 62
$LN8:
	sub	rsp, 40					; 00000028H
$LL2@transition:
; Line 67
	lea	rcx, OFFSET FLAT:?time_@@3UTime@XGK@@A	; time_
	call	?getFrameTime@TIME@XGK@@YAXPEAUTime@2@@Z ; XGK::TIME::getFrameTime
; Line 68
	lea	rcx, OFFSET FLAT:?time_@@3UTime@XGK@@A	; time_
	call	?updateTransitions@TIME@XGK@@YAXPEAUTime@2@@Z ; XGK::TIME::updateTransitions
; Line 69
	jmp	SHORT $LL2@transition
?transition_thread_function@@YAXXZ ENDP			; transition_thread_function
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?glfw_error_callback@@YAXHPEBD@Z
_TEXT	SEGMENT
error$ = 48
description$ = 56
?glfw_error_callback@@YAXHPEBD@Z PROC			; glfw_error_callback, COMDAT
; File E:\reps\denis-belov\c-test\xgk\src\test.cpp
; Line 55
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
; Line 57
	mov	ecx, 2
	mov	rbx, rdx
	call	QWORD PTR __imp___acrt_iob_func
	mov	r8, rbx
	lea	rdx, OFFSET FLAT:??_C@_0L@DCCGFMBN@Error?3?5?$CFs?6@
	mov	rcx, rax
; Line 58
	add	rsp, 32					; 00000020H
	pop	rbx
; Line 57
	jmp	fprintf
?glfw_error_callback@@YAXHPEBD@Z ENDP			; glfw_error_callback
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?glfw_key_callback@@YAXPEAUGLFWwindow@@HHHH@Z
_TEXT	SEGMENT
window$ = 48
key$ = 56
scancode$ = 64
action$ = 72
mods$ = 80
?glfw_key_callback@@YAXPEAUGLFWwindow@@HHHH@Z PROC	; glfw_key_callback, COMDAT
; File E:\reps\denis-belov\c-test\xgk\src\test.cpp
; Line 41
$LN5:
	sub	rsp, 40					; 00000028H
; Line 43
	test	r9d, r9d
	je	SHORT $LN2@glfw_key_c
; Line 46
	movss	xmm1, DWORD PTR __real@3c23d70a
	lea	rcx, OFFSET FLAT:?q@@3PAMA		; q
	call	QWORD PTR ?postRotX@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::QUAT::postRotX
; Line 47
	lea	rcx, OFFSET FLAT:?uniform_data@@3PAEA	; uniform_data
	call	?ident@MAT4@DATA@XGK@@YAXPEAX@Z		; XGK::DATA::MAT4::ident
; Line 48
	lea	rdx, OFFSET FLAT:?t@@3PAMA		; t
	lea	rcx, OFFSET FLAT:?uniform_data@@3PAEA	; uniform_data
	call	QWORD PTR ?makeTrans@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA ; XGK::DATA::MAT4::makeTrans
; Line 49
	lea	rdx, OFFSET FLAT:?q@@3PAMA		; q
	lea	rcx, OFFSET FLAT:?uniform_data@@3PAEA	; uniform_data
; Line 51
	add	rsp, 40					; 00000028H
; Line 49
	rex_jmp	QWORD PTR ?postRotQuat@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA ; XGK::DATA::MAT4::postRotQuat
$LN2@glfw_key_c:
; Line 51
	add	rsp, 40					; 00000028H
	ret	0
?glfw_key_callback@@YAXPEAUGLFWwindow@@HHHH@Z ENDP	; glfw_key_callback
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__Ftime_@@YAXXZ
text$yd	SEGMENT
??__Ftime_@@YAXXZ PROC					; `dynamic atexit destructor for 'time_'', COMDAT
	sub	rsp, 40					; 00000028H
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 1650
	mov	rcx, QWORD PTR ?time_@@3UTime@XGK@@A
	test	rcx, rcx
	je	SHORT $LN9@dynamic
; Line 1652
	mov	rdx, QWORD PTR ?time_@@3UTime@XGK@@A+16
	sub	rdx, rcx
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 867
	and	rdx, -8
; Line 186
	cmp	rdx, 4096				; 00001000H
	jb	SHORT $LN25@dynamic
; Line 107
	mov	r8, QWORD PTR [rcx-8]
	add	rdx, 39					; 00000027H
; Line 120
	sub	rcx, r8
; Line 121
	lea	rax, QWORD PTR [rcx-8]
	cmp	rax, 31
	ja	SHORT $LN22@dynamic
; Line 122
	mov	rcx, r8
$LN25@dynamic:
; Line 191
	call	??3@YAXPEAX_K@Z				; operator delete
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 1654
	xor	eax, eax
	mov	QWORD PTR ?time_@@3UTime@XGK@@A, rax
; Line 1655
	mov	QWORD PTR ?time_@@3UTime@XGK@@A+8, rax
; Line 1656
	mov	QWORD PTR ?time_@@3UTime@XGK@@A+16, rax
$LN9@dynamic:
	add	rsp, 40					; 00000028H
	ret	0
$LN22@dynamic:
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 121
	call	QWORD PTR __imp__invalid_parameter_noinfo_noreturn
	int	3
$LN32@dynamic:
??__Ftime_@@YAXXZ ENDP					; `dynamic atexit destructor for 'time_''
text$yd	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__Etime_@@YAXXZ
text$di	SEGMENT
??__Etime_@@YAXXZ PROC					; `dynamic initializer for 'time_'', COMDAT
; File E:\reps\denis-belov\c-test\xgk\src\test.cpp
; Line 26
	lea	rcx, OFFSET FLAT:??__Ftime_@@YAXXZ	; `dynamic atexit destructor for 'time_''
	jmp	atexit
??__Etime_@@YAXXZ ENDP					; `dynamic initializer for 'time_''
text$di	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1Time@XGK@@QEAA@XZ
_TEXT	SEGMENT
this$ = 48
??1Time@XGK@@QEAA@XZ PROC				; XGK::Time::~Time, COMDAT
$LN31:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 1650
	mov	rcx, QWORD PTR [rcx]
	test	rcx, rcx
	je	SHORT $LN6@Time
; Line 1652
	mov	rdx, QWORD PTR [rbx+16]
	sub	rdx, rcx
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 867
	and	rdx, -8
; Line 186
	cmp	rdx, 4096				; 00001000H
	jb	SHORT $LN22@Time
; Line 107
	mov	r8, QWORD PTR [rcx-8]
	add	rdx, 39					; 00000027H
; Line 120
	sub	rcx, r8
; Line 121
	lea	rax, QWORD PTR [rcx-8]
	cmp	rax, 31
	ja	SHORT $LN19@Time
; Line 122
	mov	rcx, r8
$LN22@Time:
; Line 191
	call	??3@YAXPEAX_K@Z				; operator delete
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 1654
	xor	eax, eax
	mov	QWORD PTR [rbx], rax
; Line 1655
	mov	QWORD PTR [rbx+8], rax
; Line 1656
	mov	QWORD PTR [rbx+16], rax
$LN6@Time:
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
$LN19@Time:
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 121
	call	QWORD PTR __imp__invalid_parameter_noinfo_noreturn
	int	3
$LN28@Time:
??1Time@XGK@@QEAA@XZ ENDP				; XGK::Time::~Time
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0Time@XGK@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0Time@XGK@@QEAA@XZ PROC				; XGK::Time::Time, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 314
	xor	eax, eax
	mov	QWORD PTR [rcx], rax
	mov	QWORD PTR [rcx+8], rax
	mov	QWORD PTR [rcx+16], rax
	mov	rax, rcx
	ret	0
??0Time@XGK@@QEAA@XZ ENDP				; XGK::Time::Time
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?_Get_first@?$_Compressed_pair@V?$allocator@PEAUTransition@XGK@@@std@@V?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@2@$00@std@@QEAAAEAV?$allocator@PEAUTransition@XGK@@@2@XZ
_TEXT	SEGMENT
this$ = 8
?_Get_first@?$_Compressed_pair@V?$allocator@PEAUTransition@XGK@@@std@@V?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@2@$00@std@@QEAAAEAV?$allocator@PEAUTransition@XGK@@@2@XZ PROC ; std::_Compressed_pair<std::allocator<XGK::Transition *>,std::_Vector_val<std::_Simple_types<XGK::Transition *> >,1>::_Get_first, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1421
	mov	rax, rcx
; Line 1422
	ret	0
?_Get_first@?$_Compressed_pair@V?$allocator@PEAUTransition@XGK@@@std@@V?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@2@$00@std@@QEAAAEAV?$allocator@PEAUTransition@XGK@@@2@XZ ENDP ; std::_Compressed_pair<std::allocator<XGK::Transition *>,std::_Vector_val<std::_Simple_types<XGK::Transition *> >,1>::_Get_first
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ PROC ; std::_Vector_val<std::_Simple_types<XGK::Transition *> >::_Vector_val<std::_Simple_types<XGK::Transition *> >, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 314
	xor	eax, eax
	mov	QWORD PTR [rcx], rax
	mov	QWORD PTR [rcx+8], rax
	mov	QWORD PTR [rcx+16], rax
; Line 315
	mov	rax, rcx
	ret	0
??0?$_Vector_val@U?$_Simple_types@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ ENDP ; std::_Vector_val<std::_Simple_types<XGK::Transition *> >::_Vector_val<std::_Simple_types<XGK::Transition *> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?_Getal@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAAEAV?$allocator@PEAUTransition@XGK@@@2@XZ
_TEXT	SEGMENT
this$ = 8
?_Getal@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAAEAV?$allocator@PEAUTransition@XGK@@@2@XZ PROC ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::_Getal, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 1689
	mov	rax, rcx
; Line 1690
	ret	0
?_Getal@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAAEAV?$allocator@PEAUTransition@XGK@@@2@XZ ENDP ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::_Getal
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?_Tidy@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAXXZ
_TEXT	SEGMENT
this$ = 48
?_Tidy@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAXXZ PROC ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::_Tidy, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 1642
$LN25:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
; Line 1650
	mov	rcx, QWORD PTR [rcx]
	test	rcx, rcx
	je	SHORT $LN2@Tidy
; Line 1652
	mov	rdx, QWORD PTR [rbx+16]
	sub	rdx, rcx
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 867
	and	rdx, -8
; Line 186
	cmp	rdx, 4096				; 00001000H
	jb	SHORT $LN18@Tidy
; Line 107
	mov	r8, QWORD PTR [rcx-8]
	add	rdx, 39					; 00000027H
; Line 120
	sub	rcx, r8
; Line 121
	lea	rax, QWORD PTR [rcx-8]
	cmp	rax, 31
	ja	SHORT $LN15@Tidy
; Line 122
	mov	rcx, r8
$LN18@Tidy:
; Line 191
	call	??3@YAXPEAX_K@Z				; operator delete
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 1654
	xor	eax, eax
	mov	QWORD PTR [rbx], rax
; Line 1655
	mov	QWORD PTR [rbx+8], rax
; Line 1656
	mov	QWORD PTR [rbx+16], rax
$LN2@Tidy:
; Line 1658
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
$LN15@Tidy:
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 121
	call	QWORD PTR __imp__invalid_parameter_noinfo_noreturn
	int	3
$LN22@Tidy:
?_Tidy@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAXXZ ENDP ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::_Tidy
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?_Destroy@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAXPEAPEAUTransition@XGK@@0@Z
_TEXT	SEGMENT
this$ = 8
_First$ = 16
_Last$ = 24
?_Destroy@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAXPEAPEAUTransition@XGK@@0@Z PROC ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::_Destroy, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 1569
	ret	0
?_Destroy@?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@AEAAXPEAPEAUTransition@XGK@@0@Z ENDP ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::_Destroy
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ
_TEXT	SEGMENT
this$ = 48
??1?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ PROC ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::~vector<XGK::Transition *,std::allocator<XGK::Transition *> >, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 623
$LN28:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
; Line 1650
	mov	rcx, QWORD PTR [rcx]
	test	rcx, rcx
	je	SHORT $LN4@vector
; Line 1652
	mov	rdx, QWORD PTR [rbx+16]
	sub	rdx, rcx
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 867
	and	rdx, -8
; Line 186
	cmp	rdx, 4096				; 00001000H
	jb	SHORT $LN20@vector
; Line 107
	mov	r8, QWORD PTR [rcx-8]
	add	rdx, 39					; 00000027H
; Line 120
	sub	rcx, r8
; Line 121
	lea	rax, QWORD PTR [rcx-8]
	cmp	rax, 31
	ja	SHORT $LN17@vector
; Line 122
	mov	rcx, r8
$LN20@vector:
; Line 191
	call	??3@YAXPEAX_K@Z				; operator delete
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 1654
	xor	eax, eax
	mov	QWORD PTR [rbx], rax
; Line 1655
	mov	QWORD PTR [rbx+8], rax
; Line 1656
	mov	QWORD PTR [rbx+16], rax
$LN4@vector:
; Line 629
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
$LN17@vector:
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 121
	call	QWORD PTR __imp__invalid_parameter_noinfo_noreturn
	int	3
$LN25@vector:
??1?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ ENDP ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::~vector<XGK::Transition *,std::allocator<XGK::Transition *> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ PROC ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::vector<XGK::Transition *,std::allocator<XGK::Transition *> >, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\vector
; Line 314
	xor	eax, eax
	mov	QWORD PTR [rcx], rax
	mov	QWORD PTR [rcx+8], rax
	mov	QWORD PTR [rcx+16], rax
; Line 388
	mov	rax, rcx
	ret	0
??0?$vector@PEAUTransition@XGK@@V?$allocator@PEAUTransition@XGK@@@std@@@std@@QEAA@XZ ENDP ; std::vector<XGK::Transition *,std::allocator<XGK::Transition *> >::vector<XGK::Transition *,std::allocator<XGK::Transition *> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?deallocate@?$allocator@PEAUTransition@XGK@@@std@@QEAAXQEAPEAUTransition@XGK@@_K@Z
_TEXT	SEGMENT
this$ = 48
_Ptr$ = 56
_Count$ = 64
?deallocate@?$allocator@PEAUTransition@XGK@@@std@@QEAAXQEAPEAUTransition@XGK@@_K@Z PROC ; std::allocator<XGK::Transition *>::deallocate, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 865
$LN21:
	sub	rsp, 40					; 00000028H
	mov	rax, rdx
; Line 867
	lea	rdx, QWORD PTR [r8*8]
; Line 186
	cmp	rdx, 4096				; 00001000H
	jb	SHORT $LN15@deallocate
; Line 107
	mov	rcx, QWORD PTR [rax-8]
	add	rdx, 39					; 00000027H
; Line 120
	sub	rax, rcx
; Line 121
	add	rax, -8
	cmp	rax, 31
	ja	SHORT $LN12@deallocate
; Line 122
	mov	rax, rcx
$LN15@deallocate:
; Line 191
	mov	rcx, rax
; Line 868
	add	rsp, 40					; 00000028H
; Line 191
	jmp	??3@YAXPEAX_K@Z				; operator delete
$LN12@deallocate:
; Line 121
	call	QWORD PTR __imp__invalid_parameter_noinfo_noreturn
	int	3
$LN18@deallocate:
?deallocate@?$allocator@PEAUTransition@XGK@@@std@@QEAAXQEAPEAUTransition@XGK@@_K@Z ENDP ; std::allocator<XGK::Transition *>::deallocate
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0?$allocator@PEAUTransition@XGK@@@std@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0?$allocator@PEAUTransition@XGK@@@std@@QEAA@XZ PROC	; std::allocator<XGK::Transition *>::allocator<XGK::Transition *>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 859
	mov	rax, rcx
	ret	0
??0?$allocator@PEAUTransition@XGK@@@std@@QEAA@XZ ENDP	; std::allocator<XGK::Transition *>::allocator<XGK::Transition *>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?simd32@DATA@XGK@@YAXXZ
_TEXT	SEGMENT
?simd32@DATA@XGK@@YAXXZ PROC				; XGK::DATA::simd32, COMDAT
; File E:\reps\denis-belov\xgk\src\data\data.h
; Line 179
$LN4:
	sub	rsp, 40					; 00000028H
; Line 181
	call	?simd32@VEC4@DATA@XGK@@YAXXZ		; XGK::DATA::VEC4::simd32
; Line 182
	call	?simd32@QUAT@DATA@XGK@@YAXXZ		; XGK::DATA::QUAT::simd32
; Line 184
	add	rsp, 40					; 00000028H
; Line 183
	jmp	?simd32@MAT4@DATA@XGK@@YAXXZ		; XGK::DATA::MAT4::simd32
?simd32@DATA@XGK@@YAXXZ ENDP				; XGK::DATA::simd32
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?join@thread@std@@QEAAXXZ
_TEXT	SEGMENT
$T1 = 32
this$ = 64
?join@thread@std@@QEAAXXZ PROC				; std::thread::join, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\thread
; Line 104
$LN14:
	push	rbx
	sub	rsp, 48					; 00000030H
; Line 101
	cmp	DWORD PTR [rcx+8], 0
; Line 104
	mov	rbx, rcx
; Line 105
	je	SHORT $LN10@join
; Line 109
	call	_Thrd_id
	cmp	DWORD PTR [rbx+8], eax
	je	SHORT $LN11@join
; Line 113
	movups	xmm0, XMMWORD PTR [rbx]
	xor	edx, edx
	lea	rcx, QWORD PTR $T1[rsp]
	movaps	XMMWORD PTR $T1[rsp], xmm0
	call	_Thrd_join
	test	eax, eax
	jne	SHORT $LN12@join
; Line 117
	xorps	xmm0, xmm0
	movups	XMMWORD PTR [rbx], xmm0
; Line 118
	add	rsp, 48					; 00000030H
	pop	rbx
	ret	0
$LN12@join:
; Line 114
	mov	ecx, 2
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN10@join:
; Line 106
	mov	ecx, 1
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN11@join:
; Line 110
	mov	ecx, 5
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN8@join:
?join@thread@std@@QEAAXXZ ENDP				; std::thread::join
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?joinable@thread@std@@QEBA_NXZ
_TEXT	SEGMENT
this$ = 8
?joinable@thread@std@@QEBA_NXZ PROC			; std::thread::joinable, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\thread
; Line 101
	cmp	DWORD PTR [rcx+8], 0
	setne	al
; Line 102
	ret	0
?joinable@thread@std@@QEBA_NXZ ENDP			; std::thread::joinable
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1thread@std@@QEAA@XZ
_TEXT	SEGMENT
this$ = 48
??1thread@std@@QEAA@XZ PROC				; std::thread::~thread, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\thread
; Line 74
$LN9:
	sub	rsp, 40					; 00000028H
; Line 101
	cmp	DWORD PTR [rcx+8], 0
; Line 75
	je	SHORT $LN2@thread
; Line 76
	call	QWORD PTR __imp_terminate
	int	3
$LN2@thread:
; Line 78
	add	rsp, 40					; 00000028H
	ret	0
$LN6@thread:
??1thread@std@@QEAA@XZ ENDP				; std::thread::~thread
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?_Alloc_proxy@_Container_base0@std@@QEAAXAEBU_Fake_allocator@2@@Z
_TEXT	SEGMENT
this$ = 8
__formal$ = 16
?_Alloc_proxy@_Container_base0@std@@QEAAXAEBU_Fake_allocator@2@@Z PROC ; std::_Container_base0::_Alloc_proxy, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1150
	ret	0
?_Alloc_proxy@_Container_base0@std@@QEAAXAEBU_Fake_allocator@2@@Z ENDP ; std::_Container_base0::_Alloc_proxy
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?_Orphan_all@_Container_base0@std@@QEAAXXZ
_TEXT	SEGMENT
this$ = 8
?_Orphan_all@_Container_base0@std@@QEAAXXZ PROC		; std::_Container_base0::_Orphan_all, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 1148
	ret	0
?_Orphan_all@_Container_base0@std@@QEAAXXZ ENDP		; std::_Container_base0::_Orphan_all
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?_Adjust_manually_vector_aligned@std@@YAXAEAPEAXAEA_K@Z
_TEXT	SEGMENT
_Ptr$ = 48
_Bytes$ = 56
?_Adjust_manually_vector_aligned@std@@YAXAEAPEAXAEA_K@Z PROC ; std::_Adjust_manually_vector_aligned, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory
; Line 102
$LN13:
	sub	rsp, 40					; 00000028H
; Line 104
	add	QWORD PTR [rdx], 39			; 00000027H
; Line 107
	mov	rax, QWORD PTR [rcx]
	mov	rdx, QWORD PTR [rax-8]
; Line 120
	sub	rax, rdx
; Line 121
	add	rax, -8
	cmp	rax, 31
	ja	SHORT $LN7@Adjust_man
; Line 122
	mov	QWORD PTR [rcx], rdx
; Line 123
	add	rsp, 40					; 00000028H
	ret	0
$LN7@Adjust_man:
; Line 121
	call	QWORD PTR __imp__invalid_parameter_noinfo_noreturn
	int	3
$LN11@Adjust_man:
?_Adjust_manually_vector_aligned@std@@YAXAEAPEAXAEA_K@Z ENDP ; std::_Adjust_manually_vector_aligned
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT fprintf
_TEXT	SEGMENT
_Stream$ = 80
_Format$ = 88
fprintf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\stdio.h
; Line 835
$LN6:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	push	rbx
	push	rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rdi, rdx
; Line 838
	lea	rsi, QWORD PTR _Format$[rsp+8]
	mov	rbx, rcx
; Line 643
	call	__local_stdio_printf_options
	xor	r9d, r9d
	mov	QWORD PTR [rsp+32], rsi
	mov	r8, rdi
	mov	rdx, rbx
	mov	rcx, QWORD PTR [rax]
	call	QWORD PTR __imp___stdio_common_vfprintf
; Line 842
	add	rsp, 48					; 00000030H
	pop	rdi
	pop	rsi
	pop	rbx
	ret	0
fprintf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _vfprintf_l
_TEXT	SEGMENT
_Stream$ = 64
_Format$ = 72
_Locale$ = 80
_ArgList$ = 88
_vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\stdio.h
; Line 642
$LN4:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rbx, r9
	mov	rdi, r8
	mov	rsi, rdx
	mov	rbp, rcx
; Line 643
	call	__local_stdio_printf_options
	mov	r9, rdi
	mov	QWORD PTR [rsp+32], rbx
	mov	r8, rsi
	mov	rdx, rbp
	mov	rcx, QWORD PTR [rax]
	call	QWORD PTR __imp___stdio_common_vfprintf
; Line 644
	mov	rbx, QWORD PTR [rsp+64]
	mov	rbp, QWORD PTR [rsp+72]
	mov	rsi, QWORD PTR [rsp+80]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
_vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_stdio_config.h
; Line 88
	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 89
	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
END
